services:
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379

  # qdrant:
  #   image: qdrant/qdrant
  #   ports:
  #     - 6333:6333
  # Commented out because using Qdrant Cloud instead

